### ISSUE TITLE
Validation reports and import reports should be stored differently

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/DAP-System#277]
Validation reports and import reports should be stored more efficiently since now they're become bigger and bigger.

To avoid OutOfMemmory errors I had to do some changes for now, see this ticket: #270

**Comment by seustachi** [comment]
@alexandru-m-g @cjhendrix can I close this one ? If not I will put it back either in the product backlog or in sprint 47

**Comment by cjhendrix** [comment]
I don't have my head in this one, so I'm not sure. @alexandru-m-g ?

**Comment by alexandru-m-g** [comment]
I think it's ok what we have so far when it comes to import logs. 
If we need something more fancy that will probably be another ticket.

**Comment by cjhendrix** [comment]
Ok, then we can close.
