### ISSUE TITLE
Server error when detect resource changes is used

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/DAP-System#346]
The following server error is generated when the https://manage.hdx.rwlabs.org/admin/status/manuallyTriggerResourcesDetection is called:

HTTP Status 500 - org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [parentdataset_revision_timestamp]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

type Exception report

message org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [parentdataset_revision_timestamp]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [parentdataset_revision_timestamp]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:391)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:534)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:482)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:419)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:439)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:178)
root cause

org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [parentdataset_revision_timestamp]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:643)
	org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:106)
	org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
	org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
	org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
	org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:270)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	com.sun.proxy.$Proxy46.newCKANResourceDetected(Unknown Source)
	org.ocha.hdx.service.HDXServiceImpl.checkForNewCKANResources(HDXServiceImpl.java:205)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
	org.ocha.hdx.tools.ExceptionAspect.handle(ExceptionAspect.java:15)
	sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	com.sun.proxy.$Proxy70.checkForNewCKANResources(Unknown Source)
	org.ocha.hdx.rest.AdminResource.manuallyTriggerResourcesDetection(AdminResource.java:880)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:534)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:482)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:419)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:439)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:178)
root cause

org.hibernate.exception.ConstraintViolationException: could not execute statement
	org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
	org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:190)
	org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
	org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3124)
	org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3587)
	org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:103)
	org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:453)
	org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:345)
	org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1218)
	org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:421)
	org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
	org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
	org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:77)
	org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:513)
	org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
	org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
	org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:270)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	com.sun.proxy.$Proxy46.newCKANResourceDetected(Unknown Source)
	org.ocha.hdx.service.HDXServiceImpl.checkForNewCKANResources(HDXServiceImpl.java:205)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
	org.ocha.hdx.tools.ExceptionAspect.handle(ExceptionAspect.java:15)
	sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	com.sun.proxy.$Proxy70.checkForNewCKANResources(Unknown Source)
	org.ocha.hdx.rest.AdminResource.manuallyTriggerResourcesDetection(AdminResource.java:880)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:534)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:482)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:419)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:439)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:178)
root cause

org.postgresql.util.PSQLException: ERROR: null value in column "parentdataset_revision_timestamp" violates not-null constraint
  Detail: Failing row contains (14b71a81-f61a-4ebd-bbbd-795b6762d805, b15f2635-c2f0-44c7-8826-681e56a62960, 2015-07-28 16:09:10.505, null, null, null, null, null, csv.zip, 3735c395-9594-4620-81d1-c395ef01955e, raw-scraperwiki-input, e50f5091-51f8-4f9c-a14a-bd88ffe0cccf, null, null, DETECTED_REVISION, 4, SCRAPER_CONFIGURABLE).
	org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
	com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147)
	org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:187)
	org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
	org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3124)
	org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3587)
	org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:103)
	org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:453)
	org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:345)
	org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1218)
	org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:421)
	org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
	org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
	org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:77)
	org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:513)
	org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
	org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
	org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:270)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	com.sun.proxy.$Proxy46.newCKANResourceDetected(Unknown Source)
	org.ocha.hdx.service.HDXServiceImpl.checkForNewCKANResources(HDXServiceImpl.java:205)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
	org.ocha.hdx.tools.ExceptionAspect.handle(ExceptionAspect.java:15)
	sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	com.sun.proxy.$Proxy70.checkForNewCKANResources(Unknown Source)
	org.ocha.hdx.rest.AdminResource.manuallyTriggerResourcesDetection(AdminResource.java:880)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:534)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:482)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:419)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:439)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:178)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.55 logs.

Apache Tomcat/7.0.55

**Comment by takavarasha** [comment]
pinging @cjhendrix

**Comment by alexandru-m-g** [comment]
The error seems to be related to the fact that neither dataset nor resource provide the revision_timestamp field on the package_show() API call. I don't think they're actually used anywhere so I think it's safe to change the code to ignore this fact.

Also, there are some issues with resources in CKAN ( probably with the scripts that are uploading data ). The download url is wrong: 
https://data.hdx.rwlabs.org/dataset/raw-fts-input
https://data.hdx.rwlabs.org/dataset/raw-scraperwiki-input
https://data.hdx.rwlabs.org/dataset/raw-reliefweb-statistics

**Comment by alexandru-m-g** [comment]
The script part of the problem was fixed by @teodorescuserban . Closing.

**Comment by alexandru-m-g** [comment]
Actually, I needed to fix one more issue related to this ( private resources were not being downloaded)
